name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Build LimboAuth
        run: ./gradlew build
      - name: Upload LimboAuth
        uses: actions/upload-artifact@v3.0.0
        with:
          name: LimboAuth Built On ${{ matrix.java }} JDK
          path: "build/libs/limboauth*.jar"
      - name: Release the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/limboauth*.jar"
          body: ${{ join(github.event.commits, '\n') }}
          prerelease: true
          name: JDK ${{ matrix.java }} Dev-build
          tag: dev-build-jdk-${{ matrix.java }}
